version: '3.9'

services:
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:9.6-alpine
    restart: always
    command: -c fsync=off -c shared_buffers=1024MB -c max_connections=1000
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - 'backend/.env'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/backend/app
      - ./backend/migrations:/backend/migrations
    depends_on:
      - postgres
    env_file:
      - 'backend/.env'
    ports:
      - "5000:5000"
      - "5678:5678"

  frontend:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - 'frontend/.env'
